package au.edu.unsw.soacourse.validater;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-02-22T22:24:11.856+08:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://soacourse.unsw.edu.au/Validater", name = "DLValidationPT")
@XmlSeeAlso({au.edu.unsw.soacourse.driverlicenseinfo.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface DLValidationPT {

    @WebMethod(action = "http://soacourse.unsw.edu.au/DLValidation/driverValidate")
    @WebResult(name = "validMessage", targetNamespace = "http://soacourse.unsw.edu.au/DriverLicenseInfo", partName = "dlresp")
    public au.edu.unsw.soacourse.driverlicenseinfo.ValidateType driverValidate(
        @WebParam(partName = "dlreq", name = "driverLicenceMessage", targetNamespace = "http://soacourse.unsw.edu.au/DriverLicenseInfo")
        au.edu.unsw.soacourse.driverlicenseinfo.DlInputType dlreq
    ) throws DriverLicenseServiceFaultMsg;
}
