
package au.edu.unsw.soacourse.validater;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.4
 * 2016-05-29T19:51:00.078+10:00
 * Generated source version: 3.0.4
 */

@WebFault(name = "serviceFaultMessage", targetNamespace = "http://soacourse.unsw.edu.au/DriverLicenseInfo")
public class DriverLicenseServiceFaultMsg extends Exception {
    
    private au.edu.unsw.soacourse.driverlicenseinfo.ServiceFaultType serviceFaultMessage;

    public DriverLicenseServiceFaultMsg() {
        super();
    }
    
    public DriverLicenseServiceFaultMsg(String message) {
        super(message);
    }
    
    public DriverLicenseServiceFaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    public DriverLicenseServiceFaultMsg(String message, au.edu.unsw.soacourse.driverlicenseinfo.ServiceFaultType serviceFaultMessage) {
        super(message);
        this.serviceFaultMessage = serviceFaultMessage;
    }

    public DriverLicenseServiceFaultMsg(String message, au.edu.unsw.soacourse.driverlicenseinfo.ServiceFaultType serviceFaultMessage, Throwable cause) {
        super(message, cause);
        this.serviceFaultMessage = serviceFaultMessage;
    }

    public au.edu.unsw.soacourse.driverlicenseinfo.ServiceFaultType getFaultInfo() {
        return this.serviceFaultMessage;
    }
}
